// Project data — 8 fictional AI projects. Layout variants drive the bento grid spans.
// Each cover is rendered procedurally from the project tags (no stock imagery).
// Order is most-recent first; `featured` flag marks the 5 highlighted on the homepage.

export const PROJECTS = [
  {
    slug: "knowledge-rag",
    name: "Knowledge RAG",
    description: "Knowledge-aware retrieval over private docs with grounded citations.",
    tags: ["RAG", "Vector DB", "Python", "Typescript"],
    github: "#",
    demo: "#",
    variant: "feature",
    span: "w9:col-span-7",
    accent: "var(--accent)",
  },
  {
    slug: "cortex-agents",
    name: "Cortex Agents",
    description: "Multi-agent research assistant that plans, searches, and writes.",
    tags: ["Agents", "Tools", "TypeScript"],
    github: "#",
    demo: "#",
    variant: "compact",
    span: "w9:col-span-5",
    accent: "#7cf6c0",
  },
  {
    slug: "prism-multimodal",
    name: "Prism Multimodal",
    description: "Vision-language document parser that turns PDFs into structured data.",
    tags: ["Multimodal", "Vision", "Eval"],
    github: "#",
    demo: "#",
    variant: "tall",
    span: "w9:col-span-4",
    accent: "#a3f5d5",
  },
  {
    slug: "forge-devtools",
    name: "Forge Dev Tools",
    description: "AI pair-programmer for legacy codebases with repo-aware context.",
    tags: ["DevTools", "LLM", "AST"],
    github: "#",
    demo: "#",
    variant: "wide",
    span: "w9:col-span-8",
    accent: "#7cf6c0",
    featured: true,
  },
  {
    slug: "helix-automation",
    name: "Helix Automation",
    description: "Workflow automation with tool-using agents and human-in-the-loop checkpoints.",
    tags: ["Agents", "Automation", "Python"],
    github: "#",
    demo: "#",
    variant: "compact",
    span: "w9:col-span-4",
    accent: "#7cf6c0",
    featured: true,
  },
  {
    slug: "quiver-eval",
    name: "Quiver Eval",
    description: "LLM evaluation harness with regression gates and rubric scoring.",
    tags: ["Evaluation", "LLMOps", "Python"],
    github: "#",
    demo: "#",
    variant: "feature",
    span: "w9:col-span-5",
    accent: "#a3f5d5",
    featured: true,
  },
  {
    slug: "lumen-local",
    name: "Lumen Local",
    description: "Local LLM deployment toolkit with model routing and offline inference.",
    tags: ["Local LLM", "Inference", "Rust"],
    github: "#",
    demo: "#",
    variant: "compact",
    span: "w9:col-span-7",
    accent: "#7cf6c0",
    featured: true,
  },
  {
    slug: "nimbus-productivity",
    name: "Nimbus Productivity",
    description: "Personal AI operating layer — email triage, calendar, and daily brief.",
    tags: ["Productivity", "Agents", "Apps"],
    github: "#",
    demo: "#",
    variant: "wide",
    span: "w9:col-span-12",
    accent: "#7cf6c0",
    featured: true,
  },
];

// The 5 most recent projects to feature on the homepage.
export const FEATURED_PROJECTS = PROJECTS.filter((p) => p.featured);
